# Generated by Django 4.2.15 on 2024-09-22 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_auto_20231103_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmember',
            name='role',
            field=models.CharField(choices=[('annotator', 'Annotator'), ('reviewer', 'Reviewer'), ('manager', 'Manager')], default='annotator', help_text='Project role', max_length=100),
        ),
    ]
